# -*- coding: utf-8 -*-
"""Pyprog

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12QTaWfcvWGSOuaG6JZcEbZtPErckn1vH
"""

#1.
# if a number is multiple of 3  but not 5, print "fizz"
# if a number is multiple of 5  but not 3, print "buzz"
# if a number is multiple of both print "fizz buzz"
# If a number is not a multiple of both then "not a fizz buzz"?

a = int(input('Give input :'))
if ((a%3)== 0 and (a%5)!=0):
   print('fizz')
elif ((a%5)==0 and (a%3)!=0):
   print('buzz')
elif ((a%3)== 0 and (a%5)==0):
   print('fizz buzz')
else:
   print('not a fizz buzz')

#2./1
# WAP to find the square root of the given value?

a = int(input('Give input:'))

if ((a)**(1/2)):
   print(f'Result is:{((a)**(1/2))}')

#2./2
# WAP to find the cube root of the given value?

a = int(input('Give input:'))

if ((a)**(1/3)):
   print(f'Result is:{((a)**(1/3))}')

#3.
# WAP to find the Roots  of the Quadratic equation?
# WAP to find the Nature of the roots along with the above?
#ax2+ bx + c = 0
a = int(input('write coeff of x2 :'))
b = int(input('write coeff of x :'))
c = int(input('write constant :'))
#quadratic equation
# b**2-4*a*c/2*a
#numerator
nr = b**2-4*a*c
#denominator
dr = 2*a
if (nr>0):
  r1 = (-b+(nr**1/2))/dr
  r2 = (-b-(nr**1/2))/dr
  print('real roots')
  print(f'root1 is :{r1}')
  print(f'root2 is :{r2}')
elif (nr == 0):
  print('equal roots')
  print(f'root1,root2 :{-b/dr}')
else:
  print('imaginary roots')

#4.
# WAP to calculate the area and perimeter of polygons(triangle, square, rectangle,circle)?
# Triangle
a = int(input('Give a:'))
b = int(input('Give b:'))
c = int(input('Give c:'))
h = int(input('Give h:'))
print(f'Perimeter = {a+b+c}')
print(f'Area = {1/2*b*h}')

#Square
a = int(input('Give a:'))
b = int(input('Give b:'))
h = int(input('Give h:'))
print(f'Perimeter = {4*a}')
print(f'Area = {b*h}')

#Rectangle
a = int(input('Give a:'))
b = int(input('Give b:'))

print(f'Area = {a*b}')
print(f'Perimeter= {2*(a+b)}')

#Circle
pi = (3.14159)
r = int(input('Give radius: '))

print(f'Perimeter = {2*pi*r}')
print(f'Area = {pi*r**2}')

#5.
# WAP to classify the amount and the quality of the purchase?
# NOTE: Consider every product is of same cost.
# Price = your_value
# quantity  = your_value
# amount = price * quantity

# amount =  ( 0 - 500 ) is low quality
# amount =  ( 501 - 1000 )is High quality
# amount =  ( 100 - 200 ) is cheaper cost
# amount =  ( 201 - 400 ) is good cost
# amount =  ( 401 - 800 ) is moderate cost
# amount =  ( 801 - 1000 )is costly

p = int(input('Price : '))
q = int(input('Quantity : '))
a = p*q
#price = 100
if (a>0 and a<=100):
   print(f'low quality, Total:{a}')
elif (a>100 and a<=200):
   print(f'low quality and cheaper cost, Total:{a}')
elif(a>200 and a<=400):
  print(f'low quality and good cost, Total:{a}')
elif(a>400 and a<=500):
  print(f'low quality and moderate cost, Total:{a}')
elif(a>500 and a<=800):
  print(f'high quality and moderate cost, Total:{a}')
else:
  print(f'high quality and costly, Total:{a}')

#6.
# Any product costs 100 each in shopping mall
# There is a discount of 10% on the bill if customer shops more than 1000 rupees
# Hint- Ask user, how many products he purchased as input to your code.
# Tell the customer the final bill.

a = int(input('How many products purchased: '))

p = (100)

if (a<10):
 print(f'Final bill:{a*p}')
else:
 print(f'Final bill:{(a*p)-(10/100*(a*p))}')

#7.
# Check whether a triangle is a scalene/isosceles/equilateral triangle?

x1 = int(input('Give x1 coordinate:'))
y1 = int(input('Give y1 coordinate:'))
x2 = int(input('Give x2 coordinate:'))
y2 = int(input('Give y2 coordinate:'))
x3 = int(input('Give x3 coordinate:'))
y3 = int(input('Give y3 coordinate:'))

side1 = (((x2 -x1)**2+(y2-y1)**2)**1/2)
side2 = (((x3-x2)**2+(y3-y2)**2)**1/2)
side3=  (((x1-x3)**2+(y1-y3)**2)**1/2)

if (side1!=side2 and side2!=side3 and side1!=side3 ):
  print('Scalene Triangle')
elif (side1==side2==side3):
  print('Equilateral Triangle')
else:
  print('Isoceles Triangle')

#8.
# students above 75% attendance should be allowed for exam
# students with permission are allowed though less than 75%

a = input('Enter student name:  ')
b = int(input('Enter number of days attended: '))
twd = 250   #total working days
attend=(b/twd)*(100)  #to calculate %
print(f'Total working days :{twd}')
if (attend>=75):
  print(f'Student allowed for exam, Attendance%:{attend}%')
else:
  print(f'Student allowed only with permission for exam, Attendance%:{attend}')

# 9.
# # Voter eligibility criteria
# 1. What is your name? (Greet user with his/her name)
# 2. Where are you from? (indian/others, only Indians are allowed to vote)
# 3. Have you ever experienced voting before? (Yes/No)
# 4. Would you like to Vote? (Yes/No)
# 5. Which Year-Month-Day were you born? (DAY/MONTH/YEAR ,Calculate age?)
# 6. Did you like our project? (Yes/No)
# 7. Please give us rating out of 5? => less than 5 ratings give 'we will try better' else 'thanks'
name = input('What is your name?')
print(f'Hello {name} welcome to voting!')

place = input('Where are you from?(India/other)')
place = place.lower()
if (place != 'india'):
    print('Sorry, you are not eligible to vote')
else:
    exp = input('Have you ever experienced voting before? (Yes/No)')
    exp = exp.lower()
    if (exp == 'yes'):
        print('Great, go ahead')
    else:
        print('Voting is important and a fundamental right for you. Please make use of it; we will check your eligibility')

    interest = input('Would you like to Vote? (Yes/No)')
    interest = interest.lower()
    if (interest != 'yes'):
      print('Thank you, you can vote next time')
    else:
      print('Awesome, let\'s do it')
        
      date = input('Which Year,date,month were you born?(DD/MM/YYYY)')
      date = str.split('/')
      year = int(date[2])
        
      if(year<2005)
       print('You are eligible')
      else:
       print('You are underage')

      like = input('Did you like our project?')
      like = like.lower()
      if(like == 'yes'):
           print('Thank you for your response')
      else:
           print('Please provide feedback')

      rating = int(input('Please give us a rating out of 5?'))
      if (rating < 5):
                print('We will try better')
      else:
                print('Thanks')



""" Building mini calculator"""

#10.
#Build Mini calculator having functionalities - *, /, +, - , %, squareroot, exponentiation, floor, ceil


operations = input('Please enter the operation you want to do :\n 1)Multiply,2)Divide,3)Add,4)Subtract,5)Percentage,6)Squareroot,7)Exponent,8)Floor,9)Ceil:    ')

if (operations =='1'):
 a = float(input('Give a value : '))
 b = float(input('Give b value : '))
 print(f'Product Result :{a*b}')
elif(operations =='2'):
 a = float(input('Give a value : '))
 b = float(input('Give b value : '))
 print(f'Quotient Result :{a/b}')
elif(operations == '3'):
  a = float(input('Give a value : '))
  b = float(input('Give b value : '))
  print(f'Sum Result :{a+b}')
elif(operations == '4'):
  a = float(input('Give a value : '))
  b = float(input('Give b value : '))
  print(f'Sub Result :{a-b}')
elif(operations == '5'):
  a = float(input('Give a value : '))
  b = float(input('Give b value : '))
  print(f'Remainder Result :{a%b}')
elif(operations == '6'):
  a = float(input('Give a value : '))
  print(f'Sq root Result :{(a)**(1/2)}')
elif(operations == '7'):
  a = float(input('Give a value : '))
  b = float(input('Give exponent value : '))
  print(f'Exponent Result :{a**b}')
elif(operations == '8'):
  a = float(input('Give a value : '))
  b = float(input('Give b value : '))
  print(f'Floor Result : {a//b}')

elif(operations == '9'):
  a = float(input('Give a value : '))
  import math
  ceil = math.ceil(a)
  print(f'Ceil Result : {ceil}')
else:
  print('Please assign a value')

# 11.
# Find greatest number among three numbers?
# ex: a,b,c are numbers
# i) a is greater
# ii) b is greater
# iii) c is greater
# iv) a, b are greater
# v) a,c are greater
# vi) b,c are greater
# vii) all are equal


a = int(input('Give value of a :'))
b = int(input('Give value of b :'))
c = int(input('Give value of c :'))

if (a>b and a>c):
  print('a is greater')
elif (b>a and b>c):
  print('b is greater')
elif (c>a and c>b):
  print('c is greater')
elif (a==b and a>c):
  print('a and b are greater and equal')
elif (a==c and a>b):
  print('a and c are greater and equal ')
elif (b==c and b>a):
  print('b and c are greater and equal ')
else:
  print('all are equal')
